### ISSUE TITLE
Reason: CORS header 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by andrewbelo** [zeekhoo-okta/okta-django-samples#10]
I am receiving this error when trying to login. I have done everything from the Basic set-up, including adding the localhost:8000 to the trusted sources in Okta console. 
I do not have a lot of experience with Django and the resources on this topic are limited. I would appreciate any feedback.

**Comment by zeekhoo** [comment]
This sample still works, even tried it just to make sure. Note that CORS is absolutely required. Here's a sample proper setup:
<img width="703" alt="Screen Shot 2021-01-15 at 8 51 18 PM" src="https://user-images.githubusercontent.com/10700898/104797528-79b9b000-5773-11eb-85db-62df0fe9e18e.png">


Also, can you share your stack trace?

**Comment by andrewbelo** [comment]
Yeah, you are right. I fixed the issue with the help of Okta support. Thank you.
