### ISSUE TITLE
okta-oauth-state keyerror on Chrom

### ISSUE THREAD

**Issue by flabbyThoroughbred** [zeekhoo-okta/okta-django-samples#11]
Hi,

Running this without any modifications and it works for Firefox. I get this error on Chrome, however:
`okta_oauth2/okta_oauth2/views.py", line 86, in callback_controller
    cookie_state = request.COOKIES["okta-oauth-state"]
KeyError: 'okta-oauth-state'`

This happens in both windows and mac for me.  Any thoughts why this is happening?

Thanks!

**Comment by zeekhoo** [comment]
Hi. Not sure if I've seen this issue before. What's your version of chrome? (I'm testing on chrome 89 without any issues). 

Could you possibly be blocking cookies? Let's try troubleshooting: Open the debugger to the Network tab. Set "Preserve Log" and load up the sample http://localhost:8000. Then search for `okta-oauth-state`:

First, you should see Set-Cookie in the Response Headers on /login:

<img width="1405" alt="Screen Shot 2021-03-15 at 10 38 22 PM" src="https://user-images.githubusercontent.com/10700898/111261368-9fcac780-85df-11eb-8c6f-6db82b707264.png">

Then you should see the `okta-oauth-state` cookie in the Request Headers to /callback:

<img width="1405" alt="Screen Shot 2021-03-15 at 10 38 06 PM" src="https://user-images.githubusercontent.com/10700898/111261441-ba9d3c00-85df-11eb-93fa-c349f205af15.png">

Let me know what you see.

**Comment by flabbyThoroughbred** [comment]
Hi. Thanks for your help!

I see no cookies in the request header. I checked in chrome and it was set to not save cookies in incognito. I even set it to save all cookies but the result was the same.

-Mark

**Comment by zeekhoo** [comment]
If you see no cookies in the request headers to /callback, it is possible that your chrome browser is "blocking all cookies." I'm not sure why though. Below is a screenshot of my setting which should work fine. Notice, I even "block 3rd party cookies in incognito", which is the default Chrome setting. In fact, blocking 3rd party cookies altogether should still work (these cookies are not 3rd party). The only setting that would give me the same error as you report is when we have "Block All Cookies" set.

<img width="639" alt="Screen Shot 2021-03-16 at 11 19 15 AM" src="https://user-images.githubusercontent.com/10700898/111360517-13092380-864a-11eb-8d23-139d40b1303a.png">

Are cookies working for other sites you visit?

**Comment by flabbyThoroughbred** [comment]
It's very odd. I haven't noticed them not working on other sites. If it helps, I'm using django 3.1.6 on python 3.8.
Also, for what it's worth, I'm using 127.0.0.1 instead of localhost as localhost is not in my trusted origins for okta.
Update: I created a localhost trusted origin. still doesn't work.

**Comment by zeekhoo** [comment]
Maybe you have old cookies on http(s)://localhost in your browser which you need to clear. Have you tried using Incognito? (FYI: ok to leave the Chrome setting "Block 3rd party cookies in incognito").

**Comment by flabbyThoroughbred** [comment]
I'm going to close this since I haven't seen the issue come up since. Chalk it up to user error.
