### ISSUE TITLE
issuer and auth_uri conflicts

### ISSUE THREAD

**Issue by flabbyThoroughbred** [zeekhoo-okta/okta-django-samples#12]
Hi,

I'm testing a couple of configurations of okta authentication. One is a development setup, the other production.

My problem is that the authorization URI wants to double of the **v1** in the like
`https://<org_url>/oauth2/v1/v1/authorize?client_id=<client_ID>`

This is what the production URIs look like:
` ISSUER: "https://<org_url>/oauth2/v1"`
`AUTH_URI: "https://<org_url/oauth2/v1/authorize"`

If I drop the **v1** on ISSUER I cannot log in at all. It claims to be a CORS Allow Missing Origin error even though the site is a valid trusted origin (and works up to the point of passing the login screen if I add the **v1** back to ISSUER).

The development URIs look like this:
`ISSUER: "https://<org_url>/oauth2/default"`
`AUTH_URI: "https://<org_url>/oauth2/default/v1/authorize"`

And they seem to work just fine. However the difference is that I'm just running this as django runserver whereas the production is being run via uwsgi as HTTPS.

Is the code in some way adding that extra **v1** to the issuer when building the authorization URL?

Thanks!

**Comment by zeekhoo** [comment]
"v1/authorize" is appended to the `issuer` property of the Signin Widget's config. This is done in `index.html`:

```
<script type="text/javascript">
var oktaSignIn = new OktaSignIn({
    baseUrl: '{{config.url}}',
    clientId: '{{config.clientId}}',
    redirectUri: '{{config.redirectUri}}',
    authParams: {
        issuer: '{{config.issuer}}',
        responseType: ['code'],
        scopes: "{{config.scope}}".split(" "),
        pkce: false
    }
});
```
The sample code only has to implement the callback handler. OAuth2 "Authorize" request is handled entirely by the Widget.

The proper values for `issuer` look like your Dev's, e.g. `https://<org-url>/oauth2/default`. Other valid values are `https://<org-url>/oauth2/{authServerId}`. On the other hand,`https://<org-url>/oauth2/v1` is never going to work.

It could be that your "Production" Org isn't enabled for "API Access Management". Can you access the AuthServer UI?
<img width="1033" alt="Screen Shot 2021-03-16 at 8 35 53 PM" src="https://user-images.githubusercontent.com/10700898/111411121-3ad2a880-8697-11eb-819c-ccfc43af9ff7.png">
This is under Security > API. (Notice the are multiple AuthServers: A "default" one, and others). If you're not seeing this, then you likely don't have the feature enabled. Get in touch with Support and they can help you out with that.

**Comment by flabbyThoroughbred** [comment]
I had the issuer incorrect all along. My mistake!
Thanks!
