### ISSUE TITLE
Logout controller questions

### ISSUE THREAD

**Issue by flabbyThoroughbred** [zeekhoo-okta/okta-django-samples#16]
Hi, 

How does the logout_controller function log out of okta? It appears to just be logging out of the django session at least as far as I can follow in the fucntion itself.
Where does it construct the openid_connect logout url? If I wanted to pass a post_logout redirect I'd need to add to the logout url. 
Is there a way to tell if it logged me out of the okta session?

Thanks!

**Comment by zeekhoo** [comment]
Hi Mark, 

Thanks for catching this. Apparently, logout from the Okta session was never implemented. I've added a commit to fix that (take a look at the new logout_controller).
The documentation for this can be found [here](https://developer.okta.com/docs/reference/api/oidc/#logout)

Note that you must configure *Logout Redirect URI* for this to work: 
* On your OIDC client, add the value `http://localhost:8000` to the list of Logout Redirect URIs

A good way to tell if you're logged in or out of the Okta session is to point your browser to `https://<your okta>.okta.com/api/v1/sessions/me`. See documentation [here.](https://developer.okta.com/docs/reference/api/sessions/#get-current-session)


Cheers.

**Comment by flabbyThoroughbred** [comment]
One thing to add. In some cases the user might have a unique post_logout_redirect_uri. Can we include something in the settings that lets the user specify that instead?

**Comment by zeekhoo** [comment]
Is there a finite list of post_logout_redirect_uri? You'd just need to whitelist all of them in the *Logout Redirect Uri* list. 

You could also be alluding to the fact that you may not know the full list beforehand. In this case, there is an alternative Okta session logout implementation you can try. See [delete session API](https://developer.okta.com/docs/reference/api/sessions/#close-current-session). What you can do is modify the logout_controller to redirect to a page that runs the above request using Javascript. (This page would also just be the "intermediate" step). When the session delete is complete, use more javascript to redirect to the final intended post_logout_redirect_uri. I'll choose not to implement the above in this sample as we're diving into corner cases that this sample code isn't meant to address. Hope this helps.

**Comment by flabbyThoroughbred** [comment]
In this case I just overrode the function that assembles the logout url to include a specific post_logout uri from settings
