### ISSUE TITLE
Base URI No Longer Present in Okta

### ISSUE THREAD

**Issue by dancaron** [zeekhoo-okta/okta-django-samples#6]
Inside Okta:
Applications > Add Application > Create New App > Web
Options are:
SWA, SAML, OpenID. Select OpenID (or any of them). 
There is no Base URI field to fill out.

**Comment by zeekhoo** [comment]
Hi Dan,

BaseURI is still there for sure. There are 2 different UIs in Okta depending on the edition you signed up for. If you signed up for the "developer" edition via https://developer.okta.com/signup, then follow the instructions in the README.

The UI looks like the following:
![Screen Shot 2020-04-21 at 4 52 43 PM](https://user-images.githubusercontent.com/10700898/79926038-c04ec980-83f0-11ea-9c7f-116d28f2ba98.png)

If you signed up a different way, you might see UI like this:
![Screen Shot 2020-04-21 at 4 53 02 PM](https://user-images.githubusercontent.com/10700898/79926061-d066a900-83f0-11ea-82b4-c8e2a7de7b35.png)
Then, follow these steps:
1) Under the Applications menu, select Applications
2) Click "Add Application"
3) Click "Create New App"
4) Choose Platform = Web, SignOnMethod = OpenID Connect
5) Fill in Application name
6) Set Login redirect URIs = http://localhost:8000/oauth2/callback/
7) Click "Save"
8) Make sure you assign to the "Everyone" group in the next step.
