### ISSUE TITLE
Error when Implicit Grant Type is Enabled

### ISSUE THREAD

**Issue by ishitvyas** [zeekhoo-okta/okta-django-samples#7]
I want to add the application in OKTA dashboard as Chiclet.
In order to do so, I enabled Implicit Grant Type.
In that case, the code is giving error:

MultiValueDictKeyError
'code'

Is there any solution for it?

**Comment by zeekhoo-okta** [comment]
Python is a Web app and thus should only use the authorization code grant type. A chicklet can be added to the dashboard by creating a "bookmark" app. Locate the bookmark app by going to Applications > Applications > Add Application > Search for "bookmark app"
