### ISSUE TITLE
how to connect with local database?? 

### ISSUE THREAD

**Issue by Rajani-salvi** [zeekhoo-okta/okta-django-samples#9]
Very nice plugin,i use it, but i need user  local database eg. i am using postgres   , user table which provide by django. 
how we can register new user from our django project if we use okta.

**Comment by zeekhoo-okta** [comment]
Hello - For provisioning Okta users to a local database, look into [event hooks](https://developer.okta.com/docs/concepts/event-hooks/) capability from Okta. If you are familiar with webhooks, that's what this is. If you're talking about the other direction (provision user from Postgres into Okta) you should use the [management APIs](https://developer.okta.com/docs/reference/api/users/)
